# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Engineers.SG Blog
email: admin@engineers.sg
description: > # this means to ignore newlines until "baseurl:"
  Engineers.SG is a not-for-profit community initiative created to help document the Singapore tech and startup scene.
  Created to answer the question, "where are the engineers in Singapore?", Engineers.SG seeks to be the place for anyone to get to know, learn and interact with the Singapore tech community. On the site, you can find a curated list of videos recording of local tech meetups and events.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.engineers.sg" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: engineersftw
github_username:  engineersftw

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
